/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojava;

/**
 *
 * @author JAIME
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        cartelSignatures = new javax.swing.JLabel();
        cartel3 = new javax.swing.JLabel();
        textoSignatures = new javax.swing.JTextField();
        textoDates = new javax.swing.JTextField();
        BuscarDates = new javax.swing.JButton();
        BuscarDates1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(0, 0, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.setBorderPainted(false);
        exit.setFocusable(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 40, 20));

        titulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 50)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 102));
        titulo.setText("WSscheduler");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, -1));

        cartelSignatures.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        cartelSignatures.setForeground(new java.awt.Color(0, 0, 204));
        cartelSignatures.setText("Signatures");
        getContentPane().add(cartelSignatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        cartel3.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        cartel3.setForeground(new java.awt.Color(0, 0, 204));
        cartel3.setText("Dates");
        getContentPane().add(cartel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        textoSignatures.setBackground(new java.awt.Color(0, 153, 153));
        textoSignatures.setForeground(new java.awt.Color(0, 0, 153));
        textoSignatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSignaturesActionPerformed(evt);
            }
        });
        getContentPane().add(textoSignatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, 30));

        textoDates.setBackground(new java.awt.Color(0, 153, 153));
        textoDates.setForeground(new java.awt.Color(0, 0, 153));
        textoDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDatesActionPerformed(evt);
            }
        });
        getContentPane().add(textoDates, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        BuscarDates.setBackground(new java.awt.Color(0, 0, 255));
        BuscarDates.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarDates.setForeground(new java.awt.Color(255, 255, 255));
        BuscarDates.setText("BUSCAR");
        BuscarDates.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BuscarDates.setBorderPainted(false);
        BuscarDates.setFocusable(false);
        BuscarDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDatesActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarDates, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        BuscarDates1.setBackground(new java.awt.Color(0, 0, 255));
        BuscarDates1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarDates1.setForeground(new java.awt.Color(255, 255, 255));
        BuscarDates1.setText("BUSCAR");
        BuscarDates1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BuscarDates1.setBorderPainted(false);
        BuscarDates1.setFocusable(false);
        BuscarDates1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDates1ActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarDates1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectojava/Imagenes/Fondo-pantalla-Samsung-Galaxy-Note-9-5.jpg"))); // NOI18N
        Fondo.setText("jLabel2");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void textoSignaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSignaturesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSignaturesActionPerformed

    private void textoDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDatesActionPerformed

    private void BuscarDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDatesActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BuscarDatesActionPerformed

    private void BuscarDates1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDates1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDates1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarDates;
    private javax.swing.JButton BuscarDates1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel cartel3;
    private javax.swing.JLabel cartelSignatures;
    private javax.swing.JButton exit;
    private javax.swing.JTextField textoDates;
    private javax.swing.JTextField textoSignatures;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
