/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojava;

/**
 *
 * @author JAIME
 */
public class PanelInicial extends javax.swing.JFrame {

    /**
     * Creates new form PanelInicial
     */
    public PanelInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        cartel1 = new javax.swing.JLabel();
        textoContraseña = new javax.swing.JPasswordField();
        textoNombre = new javax.swing.JTextField();
        cartel2 = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 50)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 102));
        titulo.setText("WSscheduler");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));

        cartel1.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        cartel1.setForeground(new java.awt.Color(0, 0, 204));
        cartel1.setText("Password");
        getContentPane().add(cartel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        textoContraseña.setBackground(new java.awt.Color(0, 153, 153));
        textoContraseña.setForeground(new java.awt.Color(0, 0, 153));
        textoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(textoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 150, 30));

        textoNombre.setBackground(new java.awt.Color(0, 153, 153));
        textoNombre.setForeground(new java.awt.Color(0, 0, 153));
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 150, 30));

        cartel2.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        cartel2.setForeground(new java.awt.Color(0, 0, 204));
        cartel2.setText("Username");
        getContentPane().add(cartel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        enter.setBackground(new java.awt.Color(0, 0, 255));
        enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enter.setForeground(new java.awt.Color(255, 255, 255));
        enter.setText("ENTER");
        enter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        enter.setBorderPainted(false);
        enter.setFocusable(false);
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 100, 30));

        exit.setBackground(new java.awt.Color(0, 0, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.setBorderPainted(false);
        exit.setFocusable(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectojava/Imagenes/Fondo-pantalla-Samsung-Galaxy-Note-9-5.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_enterActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);          // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void textoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseñaActionPerformed
       
    }//GEN-LAST:event_textoContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartel1;
    private javax.swing.JLabel cartel2;
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JLabel fondo;
    private javax.swing.JPasswordField textoContraseña;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
